export const TRADE_SECTOR_OPTIONS = [
  { value: "construction", label: "Construction / Engineering / Steel" },
  { value: "electrical", label: "Electrical Installation" },
  { value: "metalwork", label: "Architectural Metalwork" },
  { value: "it_services", label: "IT Services / Managed Service Provider (MSP)" },
  { value: "telecoms_cabling", label: "Telecoms / Network Cabling (Data)" },
  { value: "solar_ev", label: "Solar PV / Battery / EV Charging" },
  { value: "building_maintenance", label: "Building Maintenance / Facilities Management (FM)" },
  { value: "commercial_cleaning", label: "Commercial Cleaning" },
  { value: "general_construction", label: "General Construction / Building" },
  { value: "bathrooms_kitchens", label: "Bathrooms & Kitchens" },
  { value: "windows_doors", label: "Windows / Doors / Conservatories" },
  { value: "pest_control", label: "Pest Control" },
  { value: "scaffolding", label: "Scaffolding / Access Equipment" },
  { value: "mechanical_fabrication", label: "Mechanical Engineering / Fabrication" },
  { value: "fire_protection", label: "Fire Stopping / Passive Fire Protection" },
  { value: "lifts_access", label: "Lifts / Access Systems" },
  { value: "insulation_retrofit", label: "Air Tightness / Insulation / Retrofit" },
  { value: "plumbing", label: "Plumbing & Drainage" },
  { value: "hvac", label: "HVAC (Heating, Ventilation, Air Conditioning)" },
  { value: "roofing", label: "Roofing & Cladding" },
  { value: "joinery", label: "Joinery & Carpentry" },
  { value: "painting", label: "Painting & Decorating" },
  { value: "groundworks", label: "Groundworks / Civil Engineering" },
  { value: "fire_security", label: "Fire & Security Systems" },
  { value: "custom", label: "Other / Custom" },
];
