-- Phase 4A — Cover Imagery Pipeline (Delivery 12).
--
-- Adds five columns to the organizations table holding the AI-generated
-- cover hero image used as a backdrop on branded Contract/Tender (and
-- any future Project/Migration) proposals. Generated by
-- server/services/coverImageGeneration.ts via Gemini 2.5 Flash Image
-- ("Nano Banana") immediately after a successful brand extraction. The
-- image is generated once per org and reused across every proposal that
-- org sends until brand evidence changes again.
--
--   cover_image_url            permanent /api/file/<key> proxy URL of
--                              the generated PNG in R2. The renderer
--                              swaps this for a 1-hour signed URL when
--                              embedding into the print HTML, mirroring
--                              the logo-URL pattern.
--   cover_image_status         one of "idle" / "pending" / "ready" /
--                              "failed". Used as an in-flight guard and
--                              for future Settings UX surfacing.
--   cover_image_error          human-readable reason for a failed run.
--   cover_image_prompt         the actual prompt sent to Gemini, kept
--                              for debugging and prompt iteration.
--   cover_image_generated_at   timestamp of last successful generation
--                              (used for cooldown gating; default 24h).
--
-- The renderer falls back gracefully to the existing flat brand-primary
-- cover when cover_image_url is null/empty — image generation is purely
-- additive and never blocks proposal output.
--
-- Idempotent via IF NOT EXISTS — safe to re-run.

ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS cover_image_url TEXT;

ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS cover_image_status VARCHAR(20) DEFAULT 'idle';

ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS cover_image_error TEXT;

ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS cover_image_prompt TEXT;

ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS cover_image_generated_at TIMESTAMP;
