// server/services/templateRenderer.ts
//
// Phase 1 — the single render service that turns a v2.1 template plus a
// user's brand colours, slot content and logo into a PDF buffer.
//
// Pipeline:
//   1. Validate the templateId via templateLibrary.
//   2. Compute the six brand CSS variables (3 raw + 3 text-safe) plus
//      the luminance flag on our side. Per Manus's v2.1 integration note,
//      CSS color-mix chains do NOT recompute when overridden via inline
//      style in Chromium/Puppeteer, so we pre-compute and inject concrete
//      hex values.
//   3. Launch a headless Chromium via puppeteer-core + @sparticuz/chromium
//      (the slim ~50MB serverless build — keeps the Render service size
//      manageable while still giving us full CSS/font fidelity).
//   4. Load the template HTML via file:// so its relative assets/ paths
//      resolve naturally to the on-disk JPEGs, PNGs and woff2 fonts.
//   5. Inject the brand variables and the data-brand-luminance attribute
//      via page.evaluate() — runs against the real DOM, no string-parsing.
//   6. Replace [data-slot] inner content with caller-provided values.
//   7. Swap the logo placeholder for an <img> when a logoUrl is provided.
//   8. Wait for fonts + images to settle, then emit the PDF.
//
// Returns a PDF Buffer ready for the caller (Phase 2 endpoint) to stream
// to the user, store in R2, or both.
//
// IMPORTANT — do not import this module at top-level inside hot paths.
// puppeteer-core + @sparticuz/chromium pull in ~50MB of binary on first
// use; let Node lazy-load them when an export is rendered.

import * as path from "path";
import { pathToFileURL } from "url";
import puppeteer, { type Browser } from "puppeteer-core";
import chromium from "@sparticuz/chromium";

import { getTemplate, type TemplateDef } from "./templateLibrary";
import { resolveBrandRenderVars, type BrandInput, type BrandRenderVars } from "./colourUtils";

// ── Types ───────────────────────────────────────────────────────────

/**
 * Caller-supplied slot content. Keys are data-slot attribute values
 * (e.g. "about-text", "company-name", "summary-text"); values are the
 * HTML or text to inject into each slot.
 *
 * Slots not in this map are left with whatever sample content Manus
 * shipped — useful for partial previews where only some content has
 * been generated by the AI pipeline. Phase 2 will populate the full
 * set; Phase 1 test script populates a hardcoded subset.
 */
export type SlotContent = Record<string, string>;

export interface RenderTemplateOptions {
  /** Template id in "sector/style" form, e.g. "it-services/01-split-screen". */
  templateId: string;
  /** User's brand colours from the organizations table. */
  brand: BrandInput;
  /** Content to inject into [data-slot] elements. Slots not in this
   *  map are left as the template's sample content. */
  slotContent?: SlotContent;
  /** Absolute URL or file:// path to the user's logo image. When set,
   *  the logo placeholder is replaced with an <img> tag. */
  logoUrl?: string | null;
  /** Override PDF format. Defaults to A4 portrait. */
  format?: "A4";
  /** Override puppeteer launch timeout in milliseconds. Default 30s. */
  launchTimeoutMs?: number;
}

export interface RenderTemplateResult {
  /** The rendered PDF as a Buffer. */
  pdf: Buffer;
  /** Resolved template definition — useful for callers that want to
   *  log or persist which template was rendered. */
  template: TemplateDef;
  /** The brand variables actually used. Exposed for debugging. */
  brand: BrandRenderVars;
  /** Total render time in milliseconds. */
  durationMs: number;
}

// ── Public API ──────────────────────────────────────────────────────

/**
 * Render a template to a PDF Buffer. Single public entry point.
 *
 * Throws if templateId is invalid or the underlying Chromium render
 * fails. Callers should wrap in try/catch and surface a user-friendly
 * error — the underlying puppeteer errors are not for end users.
 */
export async function renderTemplate(
  options: RenderTemplateOptions,
): Promise<RenderTemplateResult> {
  const startedAt = Date.now();

  // 1. Resolve template
  const template = getTemplate(options.templateId);
  if (!template) {
    throw new Error(`Unknown templateId: ${options.templateId}`);
  }

  // 2. Compute brand variables
  const brand = resolveBrandRenderVars(options.brand);

  // 3. Launch Chromium
  const browser = await launchBrowser(options.launchTimeoutMs ?? 30_000);
  try {
    const page = await browser.newPage();

    // 4. Load the template via file:// so relative asset paths resolve
    //    naturally. waitUntil "networkidle0" gives fonts + images time
    //    to load before we attempt to render the PDF.
    const fileUrl = pathToFileURL(template.htmlPath).toString();
    await page.goto(fileUrl, { waitUntil: "networkidle0", timeout: 60_000 });

    // 5–7. Apply all DOM mutations in a single evaluate() — atomic and
    //      easier to debug than multiple round-trips.
    await page.evaluate(applyTemplateMutations, {
      brand,
      slotContent: options.slotContent ?? {},
      logoUrl: options.logoUrl ?? null,
    });

    // Belt-and-braces: wait for any newly-injected logo image to load.
    // page.evaluate above can complete before an <img> finishes loading
    // from a remote URL, which would result in a missing image in the PDF.
    if (options.logoUrl) {
      await page.evaluate(() => {
        const imgs = Array.from(document.querySelectorAll('img[data-injected-logo="true"]'));
        return Promise.all(
          imgs.map((img) => {
            const el = img as HTMLImageElement;
            if (el.complete) return Promise.resolve();
            return new Promise<void>((resolve) => {
              el.addEventListener("load", () => resolve(), { once: true });
              el.addEventListener("error", () => resolve(), { once: true }); // don't block on a bad logo URL
            });
          }),
        );
      });
    }

    // 8. Emit PDF
    const pdf = (await page.pdf({
      format: options.format ?? "A4",
      printBackground: true,
      preferCSSPageSize: true,
      // Margins handled by the template's CSS (the @page rule + per-section
      // padding). preferCSSPageSize: true honours those rather than fighting
      // them with separate puppeteer margins.
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
    })) as Buffer;

    return {
      pdf,
      template,
      brand,
      durationMs: Date.now() - startedAt,
    };
  } finally {
    await browser.close();
  }
}

// ── Internals ───────────────────────────────────────────────────────

async function launchBrowser(timeoutMs: number): Promise<Browser> {
  // @sparticuz/chromium ships a slim Chromium binary suitable for
  // serverless / containerised environments. executablePath() returns
  // the unpacked binary's location.
  const executablePath = await chromium.executablePath();
  return puppeteer.launch({
    args: chromium.args,
    executablePath,
    headless: true,
    timeout: timeoutMs,
  });
}

/**
 * Runs inside the browser context (page.evaluate). Receives the brand
 * variables, slot content map, and logo URL as a single payload object.
 *
 * IMPORTANT: this function is serialised across to the browser context.
 * It must not reference outer-scope variables or import statements.
 * Keep it self-contained.
 */
function applyTemplateMutations(payload: {
  brand: BrandRenderVars;
  slotContent: SlotContent;
  logoUrl: string | null;
}): void {
  const { brand, slotContent, logoUrl } = payload;

  // 1. Inject brand CSS variables. A style tag appended to <head>
  //    after the template's own :root declarations wins the cascade.
  const styleTag = document.createElement("style");
  styleTag.setAttribute("data-injected-brand", "true");
  styleTag.textContent = `:root {
    --brand-primary: ${brand.brandPrimary};
    --brand-secondary: ${brand.brandSecondary};
    --brand-accent: ${brand.brandAccent};
    --brand-primary-text-safe: ${brand.brandPrimaryTextSafe};
    --brand-secondary-text-safe: ${brand.brandSecondaryTextSafe};
    --brand-accent-text-safe: ${brand.brandAccentTextSafe};
  }`;
  document.head.appendChild(styleTag);

  // 2. Set the luminance flag on <html> when the brand is pale, so
  //    Manus's data-brand-luminance="light" fallback rules activate.
  if (brand.isLightBrand) {
    document.documentElement.setAttribute("data-brand-luminance", "light");
  }

  // 3. Replace slot content. Each data-slot attribute may appear on
  //    multiple elements (e.g. "date" appears in the meta block and
  //    in the footer of some designs) — we replace ALL matching
  //    elements' innerHTML.
  for (const [slotKey, slotValue] of Object.entries(slotContent)) {
    const targets = document.querySelectorAll<HTMLElement>(`[data-slot="${slotKey}"]`);
    targets.forEach((el) => {
      el.innerHTML = slotValue;
    });
  }

  // 4. Logo placeholder swap. The templates ship with a
  //    <div data-slot="logo"><div class="logo-box">YOUR LOGO HERE</div></div>
  //    placeholder. Replace the inner with an <img> when a logoUrl is
  //    provided.
  if (logoUrl) {
    const logoSlots = document.querySelectorAll<HTMLElement>('[data-slot="logo"]');
    logoSlots.forEach((slot) => {
      // Preserve any sizing the template applied to the slot wrapper;
      // we just swap the inner content.
      slot.innerHTML = `<img src="${escapeAttr(logoUrl)}" alt="" data-injected-logo="true" style="max-width: 100%; max-height: 100%; display: block; object-fit: contain;" />`;
    });
  }

  // Helper — guard against quote/angle-bracket injection in the logo URL.
  // Inline because page.evaluate can't reach outer-scope functions.
  function escapeAttr(s: string): string {
    return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }
}
